language: go
sudo: false
go:
  - 1.5
  - 1.6

install:
  - go get github.com/coreos/etcd
  - go get github.com/mwitkow/go-etcd-harness
  - go get github.com/stretchr/testify
  - go get github.com/spf13/pflag

script:
 - go test -short -race -v ./...
